repos:
- repo: https://github.com/python/black
  rev: 22.1.0
  hooks:
    - id: black
      language_version: python
      exclude: ^(.*\b(migrations)\b.*|.*\b(venv)\b.*)$
      additional_dependencies: ['click==8.0.4']
      args: [--line-length=79]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      exclude: ^(.*\b(migrations)\b.*|.*\b(venv)\b.*)$
      additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify