version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    command: ./docker-entrypoint-local.sh
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    working_dir: /app/api/
    networks:
      - api

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: always
    networks:
      - api

networks:
  api:
