name: Generate FastAPI OpenAPI specification
on: 
  push
jobs:
  generate-specification:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Generate OpenAPI file
        env:
          POSTGRES_SERVER: localhost
          SSL_MODE: prefer
          SECRET_KEY: SECRET_KEY
          REFRESH_SECRET_KEY: REFRESH_SECRET_KEY
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        run: |
          pipenv install --dev pyyaml
          pipenv run python scripts/generate_openapi.py

      - name: Generate unique change name
        run: |
          UNIQUE_CHANGE_NAME="update_api_specification_$(date +%F_%H-%M-%S)"
          echo "UNIQUE_CHANGE_NAME=$UNIQUE_CHANGE_NAME" >> $GITHUB_ENV

      - name: Git push and commit remote
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git config --global credential.helper cache
          git clone https://${{secrets.ACCESS_TOKEN}}@github.com/mskab/ePetition-docs
          cp openapi.yml ePetition-docs/ -f
          cd ePetition-docs
          git checkout -b ${{env.UNIQUE_CHANGE_NAME}}
          git add .
          git commit -m "$(date)"
          git push -f -u origin ${{env.UNIQUE_CHANGE_NAME}}

      - name: Open PR remote
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PULL_REQUEST_REPOSITORY: https://github.com/mskab/ePetition-docs
          PULL_REQUEST_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_FROM_BRANCH: ${{env.UNIQUE_CHANGE_NAME}}
          PULL_REQUEST_TITLE: Update API docs
