name: Generate FastAPI OpenAPI specification
on: 
  push
jobs:
  generate-specification:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Generate OpenAPI file
        env:
          POSTGRES_SERVER: localhost
          SSL_MODE: prefer
          SECRET_KEY: SECRET_KEY
          REFRESH_SECRET_KEY: REFRESH_SECRET_KEY
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        run: |
          pipenv install --dev pyyaml
          pipenv run python scripts/generate_openapi.py

      - name: Git push and commit remote
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          export UNIQUE_CHANGE_NAME="update/api-specification-$(date +%F_%H-%M-%S)"

          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git config --global credential.helper cache

          git clone https://${ACCESS_TOKEN}@github.com/mskab/ePetition-docs

          cd ePetition-docs
          git checkout -b ${UNIQUE_CHANGE_NAME}
          cp ../openapi.yml ./ -f
          git add .

          if git diff-index --quiet HEAD --; then
            export FILE_CHANGE= "false"
            printf "No changes\n"
          else
            export FILE_CHANGE= "true"
            printf "Changes\n"
            git commit -m "Automated update API spec $(date +%Y-%m-%d)"
            git push -f -u origin ${UNIQUE_CHANGE_NAME}
          fi
          echo "PULL_REQUEST_FROM_BRANCH=${UNIQUE_CHANGE_NAME}" >> $GITHUB_ENV
          echo "IS_CHANGE=${FILE_CHANGE}" >> $GITHUB_ENV

        - if: ${{ env.IS_CHANGE }} == "true"
          name: Open PR remote
          uses: vsoch/pull-request-action@master
          env:
            PULL_REQUEST_REPOSITORY: mskab/ePetition-docs
            PULL_REQUEST_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            PULL_REQUEST_BRANCH: main
