name: Generate FastAPI OpenAPI specification
on: 
  push
jobs:
  generate-specification:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Generate OpenAPI file
        run: |
          pip install fastapi pyyaml
          python scripts/generate_openapi.py

        - name: Generate UNIQUE_CHANGE_NAME
          run: |
            UNIQUE_CHANGE_NAME=$(date +%F_%H-%M-%S)
            echo "UNIQUE_CHANGE_NAME=`update_api_specification_${UNIQUE_CHANGE_NAME}`" >> $GITHUB_ENV


      - name: Commit changes in remote repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.UNIQUE_CHANGE_NAME }}
          branch: ${{ env.UNIQUE_CHANGE_NAME }}
          repository: https://github.com/mskab/ePetition-docs
          file_pattern: "openapi.yml"
          create_branch: true

      - name: Open PR in remote repo
        uses: vsoch/pull-request-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_REPOSITORY: https://github.com/mskab/ePetition-docs
          PULL_REQUEST_TOKEN: ${{ secrets.PAT }}
          PULL_REQUEST_BRANCH: main
          PULL_REQUEST_FROM_BRANCH: ${{env.UNIQUE_CHANGE_NAME}}
          PULL_REQUEST_TITLE: Update API docs
