name: Generate FastAPI OpenAPI specification
on: 
  push
jobs:
  generate-specification:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checks out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Generate OpenAPI file
        env:
          POSTGRES_SERVER: localhost
          SSL_MODE: prefer
          SECRET_KEY: SECRET_KEY
          REFRESH_SECRET_KEY: REFRESH_SECRET_KEY
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        run: |
          pipenv install --dev pyyaml
          pipenv run python scripts/generate_openapi.py

      - name: Git push and commit remote
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          UNIQUE_CHANGE_NAME="update/api-specification-$(date +%F_%H-%M-%S)"
          FILE_CHANGE='false'

          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git config --global credential.helper cache

          git clone https://$ACCESS_TOKEN@github.com/mskab/ePetition-docs

          cd ePetition-docs
          git checkout -b $UNIQUE_CHANGE_NAME
          cp ../openapi.yml ./ -f
          git add .

          if git diff-index --quiet HEAD --; then
            echo "No changes"
          else
            FILE_CHANGE='true'
            echo "Changes"
            git commit -m "Automated update API spec $(date +%Y-%m-%d)"
            git push -f -u origin $UNIQUE_CHANGE_NAME
          fi
          echo "PULL_REQUEST_FROM_BRANCH=$UNIQUE_CHANGE_NAME" >> $GITHUB_ENV
          echo "IS_CHANGE=$FILE_CHANGE" >> $GITHUB_ENV

      - name: Open PR remote
        env:
          PULL_REQUEST_REPOSITORY: mskab/ePetition-docs
          PULL_REQUEST_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PULL_REQUEST_BRANCH: main
        if: ${{ env.IS_CHANGE == 'true' }}
        uses: vsoch/pull-request-action@master
